//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Storage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRAK
    {
        public int ID_BRAK { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> quanity { get; set; }
        public byte[] Photo { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> DataOtgruz { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
        public virtual users users { get; set; }
    }
}
