//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Storage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKLAD
    {
        public int ID_SKLAD { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Kolvo { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
    }
}
