//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Storage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_form
    {
        public int ID_USFORM { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string patronymic { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual users users { get; set; }
    }
}
